version: '2'

networks:
  microservice-tier:
    driver: bridge
  ops-tier:
    driver: bridge

services:
  eureka-server1.demo.svc.cluster.local:
    image: servicehive/eureka-server:1.0.2
    environment:
      - ACTIVE_PROFILE=peer1
    ports:
      - 8761:8761  
    networks:
      - microservice-tier
      - ops-tier
      
  eureka-server2.demo.svc.cluster.local:
    image: servicehive/eureka-server:1.0.2
    environment:
      - ACTIVE_PROFILE=peer2
    ports:
      - 8762:8761
    networks:
      - microservice-tier
      - ops-tier

  demo-hr-service.demo.svc.cluster.local:
    image: servicehive/demo-hr-kenly:1.0.2
    ports:
      - 8080:8080
    networks:
      - microservice-tier